name: organoid-analysis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python环境
  - python=3.9
  - pip>=21.0
  
  # 科学计算基础包
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  
  # 图像处理
  - scikit-image>=0.18.0
  - pillow>=8.2.0
  - opencv>=4.5.0
  
  # 深度学习框架
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - cudatoolkit=11.3
  
  # 机器学习
  - scikit-learn>=0.24.0
  
  # 可视化
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # 数据处理
  - pyyaml>=5.4.0
  - h5py>=3.3.0
  - pytables>=3.6.1
  
  # 工具包
  - tqdm>=4.61.0
  - joblib>=1.0.0
  
  # 开发工具
  - pytest>=6.2.0
  - black>=21.6b0
  - flake8>=3.9.0
  - jupyter>=1.0.0
  - ipywidgets>=7.6.0
  
  # pip安装的包
  - pip:
    - segment-anything>=1.0
    - transformers>=4.11.0
    - isort>=5.9.0
    - tensorboard>=2.6.0
    - albumentations>=1.0.0
    - wandb>=0.12.0  # 实验跟踪
    - timm>=0.4.12   # 模型库
    
  # CUDA相关
variables:
  CUDA_HOME: /usr/local/cuda
  TORCH_CUDA_ARCH_LIST: "6.0 6.1 7.0 7.5 8.0 8.6" 